# Setup
title:               Uprising 518
tagline:             'Gwangju Uprising'
description:         'Gwanju Uprising 5.18. Let us dial 062-518(Ma City-BTS in Young Forever /PDOGG, BANG, RM, SUGA, j-hope'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
